# Generated by Django 5.2.7 on 2025-10-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erosion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capteur',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='capteur',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='latitude_centre',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='longitude_centre',
        ),
        migrations.AddField(
            model_name='capteur',
            name='position_json',
            field=models.TextField(default=1, help_text='Position au format GeoJSON'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zone',
            name='geometrie_json',
            field=models.TextField(help_text='Géométrie au format GeoJSON'),
        ),
    ]
