# Generated by Django 5.2.7 on 2025-10-09 16:26

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erosion', '0002_remove_capteur_latitude_remove_capteur_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capteur',
            name='position_json',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='geometrie_json',
        ),
        migrations.AddField(
            model_name='capteur',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='zone',
            name='geometrie',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
