# Generated by Django 5.2.7 on 2025-10-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erosion', '0005_capteurarduino_donneesmanquantes_logcapteurarduino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesurearduino',
            name='humidite',
            field=models.FloatField(blank=True, help_text='Humidité relative (%)', null=True),
        ),
        migrations.AlterField(
            model_name='capteurarduino',
            name='etat',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('detected', 'Détecté'), ('maintenance', 'En maintenance'), ('defaillant', 'Défaillant'), ('hors_ligne', 'Hors ligne'), ('erreur_wifi', 'Erreur Wi-Fi')], default='inactif', max_length=20),
        ),
        migrations.AlterField(
            model_name='mesurearduino',
            name='valeur',
            field=models.FloatField(help_text='Valeur principale (température)'),
        ),
    ]
