# Generated by Django 5.2.7 on 2025-10-15 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erosion', '0008_rename_parametres_modele_prediction_parametres_prediction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedonnees',
            name='type_donnees',
            field=models.CharField(choices=[('mesures_arduino', 'Mesures Arduino'), ('evenements_externes', 'Événements externes'), ('evenements_erosion_cotiere', 'Événements érosion côtière'), ('fusions', 'Fusions de données'), ('predictions', 'Prédictions'), ('alertes', 'Alertes')], max_length=30),
        ),
        migrations.CreateModel(
            name='EvenementErosionCotiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('tempete_cotiere_majeure', 'Tempête Côtière Majeure'), ('tempete_cotiere_moderee', 'Tempête Côtière Modérée'), ('tempete_cotiere_faible', 'Tempête Côtière Faible'), ('ouragan', 'Ouragan'), ('cyclone', 'Cyclone'), ('tsunami', 'Tsunami'), ('maree_exceptionnelle', 'Marée Exceptionnelle'), ('secheresse', 'Sécheresse'), ('inondation', 'Inondation'), ('autre', 'Autre')], max_length=50)),
                ('category', models.CharField(choices=[('minor', 'Mineur'), ('moderate', 'Modéré'), ('major', 'Majeur'), ('extreme', 'Extrême')], max_length=20)),
                ('intensite', models.CharField(help_text='Intensité (ex: 8-12m)', max_length=20)),
                ('duree', models.CharField(help_text='Durée (ex: 48-72h)', max_length=20)),
                ('date', models.DateTimeField(help_text="Date/heure de l'événement")),
                ('impact', models.TextField(help_text="Description de l'impact")),
                ('risk', models.CharField(choices=[('faible', 'Faible'), ('modere', 'Modéré'), ('eleve', 'Élevé'), ('critique', 'Critique')], max_length=20)),
                ('probability', models.CharField(help_text='Probabilité (ex: 15%)', max_length=10)),
                ('affected_area', models.CharField(help_text='Zone affectée', max_length=100)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('prevision', 'Prévision'), ('alerte', 'Alerte')], max_length=20)),
                ('erosion_data', models.JSONField(default=dict, help_text="Données d'érosion détaillées")),
                ('parameters_detailed', models.JSONField(default=dict, help_text='Paramètres détaillés')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp de réception')),
                ('source', models.CharField(help_text="Source de l'événement", max_length=100)),
                ('version', models.CharField(default='1.0', help_text='Version du format', max_length=10)),
                ('network_info', models.JSONField(default=dict, help_text='Informations réseau')),
                ('is_traite', models.BooleanField(default=False, help_text='Événement traité par le système')),
                ('is_valide', models.BooleanField(default=True, help_text='Événement validé')),
                ('is_simulation', models.BooleanField(default=False, help_text='Données de simulation')),
                ('commentaires', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_erosion_cotiere', to='erosion.zone')),
            ],
            options={
                'verbose_name': 'Événement Érosion Côtière',
                'verbose_name_plural': 'Événements Érosion Côtière',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['type', 'category'], name='erosion_eve_type_13d20f_idx'), models.Index(fields=['date', 'statut'], name='erosion_eve_date_c3730e_idx'), models.Index(fields=['risk', 'probability'], name='erosion_eve_risk_933921_idx'), models.Index(fields=['source', 'timestamp'], name='erosion_eve_source_e9483b_idx'), models.Index(fields=['is_traite', 'is_valide'], name='erosion_eve_is_trai_ec8019_idx')],
            },
        ),
    ]
