# Generated by Django 5.2.7 on 2025-10-15 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erosion', '0009_add_evenement_erosion_cotiere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenementerosioncotiere',
            name='zone',
        ),
        migrations.RemoveIndex(
            model_name='evenementexterne',
            name='erosion_eve_zone_id_a0caaa_idx',
        ),
        migrations.RemoveField(
            model_name='evenementexterne',
            name='description',
        ),
        migrations.RemoveField(
            model_name='evenementexterne',
            name='duree_minutes',
        ),
        migrations.RemoveField(
            model_name='evenementexterne',
            name='evenements_lies',
        ),
        migrations.RemoveField(
            model_name='evenementexterne',
            name='intensite_categorie',
        ),
        migrations.RemoveField(
            model_name='evenementexterne',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='evenementexterne',
            name='rayon_impact_km',
        ),
        migrations.RemoveField(
            model_name='evenementexterne',
            name='source_id',
        ),
        migrations.AddField(
            model_name='evenementexterne',
            name='donnees_meteo',
            field=models.JSONField(default=dict, help_text='Données météo supplémentaires'),
        ),
        migrations.AddField(
            model_name='evenementexterne',
            name='duree',
            field=models.CharField(default='1h', help_text="Durée de l'événement (ex: 2h, 30min)", max_length=20),
        ),
        migrations.AddField(
            model_name='evenementexterne',
            name='id_source',
            field=models.IntegerField(blank=True, help_text="ID unique de l'événement dans la source", null=True),
        ),
        migrations.AddField(
            model_name='evenementexterne',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude', null=True),
        ),
        migrations.AddField(
            model_name='evenementexterne',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude', null=True),
        ),
        migrations.AddField(
            model_name='evenementexterne',
            name='niveau_risque',
            field=models.CharField(choices=[('faible', 'Faible'), ('modere', 'Modéré'), ('eleve', 'Élevé'), ('critique', 'Critique')], default='faible', help_text='Niveau de risque calculé automatiquement', max_length=20),
        ),
        migrations.AddField(
            model_name='evenementexterne',
            name='statut',
            field=models.CharField(choices=[('envoye', 'Envoyé'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('recu', 'Reçu')], default='recu', max_length=20),
        ),
        migrations.AddField(
            model_name='evenementexterne',
            name='zone_erosion',
            field=models.CharField(choices=[('non_determinee', 'Non déterminée'), ('cotes_rocheuses', 'Côtes rocheuses'), ('dunes_cotieres', 'Dunes côtières'), ('plages_sableuses', 'Plages sableuses'), ('zones_basses', 'Zones basses'), ('falaises', 'Falaises'), ('estuaires', 'Estuaires')], default='non_determinee', help_text="Zone d'érosion affectée", max_length=30),
        ),
        migrations.AlterField(
            model_name='archivedonnees',
            name='type_donnees',
            field=models.CharField(choices=[('mesures_arduino', 'Mesures Arduino'), ('evenements_externes', 'Événements externes'), ('fusions', 'Fusions de données'), ('predictions', 'Prédictions'), ('alertes', 'Alertes')], max_length=30),
        ),
        migrations.AlterField(
            model_name='evenementexterne',
            name='intensite',
            field=models.FloatField(help_text="Intensité de l'événement"),
        ),
        migrations.AlterField(
            model_name='evenementexterne',
            name='is_simulation',
            field=models.BooleanField(default=False, help_text='Données de simulation'),
        ),
        migrations.AlterField(
            model_name='evenementexterne',
            name='is_traite',
            field=models.BooleanField(default=False, help_text='Événement traité par le système'),
        ),
        migrations.AlterField(
            model_name='evenementexterne',
            name='is_valide',
            field=models.BooleanField(default=True, help_text='Événement validé'),
        ),
        migrations.AlterField(
            model_name='evenementexterne',
            name='source',
            field=models.CharField(choices=[('manuel', 'Manuel'), ('capteur', 'Capteur'), ('api', 'API'), ('externe', 'Externe')], default='externe', max_length=20),
        ),
        migrations.AlterField(
            model_name='evenementexterne',
            name='type_evenement',
            field=models.CharField(choices=[('pluie', 'Pluie'), ('vent_fort', 'Vent fort'), ('houle', 'Houle'), ('maree_haute', 'Marée haute'), ('tempete', 'Tempête'), ('ouragan', 'Ouragan'), ('cyclone', 'Cyclone'), ('tsunami', 'Tsunami'), ('maree_exceptionnelle', 'Marée exceptionnelle'), ('secheresse', 'Sécheresse'), ('inondation', 'Inondation'), ('autre', 'Autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='evenementexterne',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_externes', to='erosion.zone'),
        ),
        migrations.AddIndex(
            model_name='evenementexterne',
            index=models.Index(fields=['date_evenement', 'statut'], name='erosion_eve_date_ev_7cfd8a_idx'),
        ),
        migrations.AddIndex(
            model_name='evenementexterne',
            index=models.Index(fields=['niveau_risque', 'zone_erosion'], name='erosion_eve_niveau__58a2b7_idx'),
        ),
        migrations.DeleteModel(
            name='EvenementErosionCotiere',
        ),
    ]
