# Generated by Django 5.2.7 on 2025-10-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erosion', '0010_update_evenement_externe_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerte',
            name='date_resolution',
        ),
        migrations.RemoveField(
            model_name='alerte',
            name='est_resolue',
        ),
        migrations.RemoveField(
            model_name='alerte',
            name='niveau',
        ),
        migrations.RemoveField(
            model_name='alerte',
            name='type',
        ),
        migrations.RemoveField(
            model_name='alerte',
            name='utilisateur_creation',
        ),
        migrations.RemoveField(
            model_name='alerte',
            name='utilisateur_resolution',
        ),
        migrations.AddField(
            model_name='alerte',
            name='date_mise_a_jour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='alerte',
            name='donnees_marines',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='alerte',
            name='donnees_meteo',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='alerte',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='alerte',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='alerte',
            name='niveau_urgence',
            field=models.CharField(choices=[('faible', 'Faible'), ('modéré', 'Modéré'), ('élevé', 'Élevé'), ('critique', 'Critique')], default='faible', max_length=20),
        ),
        migrations.AddField(
            model_name='alerte',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alerte',
            name='statut',
            field=models.CharField(choices=[('active', 'Active'), ('resolue', 'Résolue'), ('archivée', 'Archivée')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='alerte',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='alerte',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alerte',
            name='titre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='alerte',
            name='zone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='alerte',
            table='alertes',
        ),
    ]
